[package]
name = "hourglass"
version = "0.1.0"
authors = ["Jan <goarano@gmail.com>"]

[dependencies]
chrono = { version = "0.3", features = ["serde"] }
serde = "1.0"
serde_derive = "1.0"
rusqlite = "0.11"